### ISSUE TITLE
change password page has optional on fields that should be required

### ISSUE THREAD

**Issue by PromiseFru** [smswithoutborders/smswithoutborders.com#23]
![image](https://user-images.githubusercontent.com/15856785/156544740-5cfe2ff9-a991-4b97-a2ac-acca802e38f5.png)

**Comment by nSedrickm** [comment]
Thanks @PromiseFru. The [label component](https://github.com/smswithoutborders/smswithoutborders.com/blob/17f1e1eae9936df565669dd6bc4791f821a46efe/src/components/shared.js#L36-L47) got updated recently to show optional by default. This can be fixed by adding a required attribute to each label on the [password change](https://github.com/smswithoutborders/smswithoutborders.com/blob/dev/src/pages/settings/PasswordChange.js) page. I will leave this open for now

**Comment by Olaleye-Blessing** [comment]
Can I work on this?

**Comment by nSedrickm** [comment]
Hi, yes you can. You can take a look at our [contribution guide](https://github.com/smswithoutborders/smswithoutborders.com/blob/dev/docs/CONTRIBUTING.md) to help you get started with the project.

The most recent changes to this project can be found in the [#dev](https://github.com/smswithoutborders/smswithoutborders.com/tree/dev) branch. I encourage you to branch from there, make changes then open a  pull request to the #dev branch. Let me know if you need any help.

**Comment by Olaleye-Blessing** [comment]
I need help with working from [dev](https://github.com/smswithoutborders/smswithoutborders.com/tree/dev) branch.
I've forked and cloned the repository, but I have the master instead of dev.

**Comment by Olaleye-Blessing** [comment]
![Screenshot (188)](https://user-images.githubusercontent.com/70102539/157925267-68cf5e5c-efe3-4fba-b9e6-5aa659dadefc.png)

**Comment by nSedrickm** [comment]
Hi, This is perfect thank you. I think you meant to attach it on the pull request instead but its ok. These things can be confusing

**Comment by nSedrickm** [comment]
Thanks for your contribution. closing this in favour of #27
